FROM nginx:stable-alpine

# Xóa content mặc định
RUN rm -rf /usr/share/nginx/html/*

# Copy các file build frontend từ volume hoặc từ folder build
COPY ./SHOESYEE-WEB-PROJECT/dist/loi/browser/* /usr/share/nginx/html/

# Copy nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Set permissions cho thư mục
RUN chown -R nginx:nginx /usr/share/nginx/html && \
    chmod -R 755 /usr/share/nginx/html
