// src/app/mock-products.ts

import { Product } from '../interface/Product';


export const DATA_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Nike Air Max',
    brand: 'Nike',
    category: 'Shoes',
    type: 'Running',
    colors: ['Black', 'White', 'Red'],
    sizes: [38, 39, 40, 41],
    price: 120,
    discountPercentage: 10,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 2,
    name: 'Adidas Ultraboost',
    brand: 'Adidas',
    category: 'Shoes',
    type: 'Running',
    colors: ['Blue', 'White', 'Gray'],
    sizes: [38, 39, 40, 41, 42],
    price: 180,
    discountPercentage: 0,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 3,
    name: 'Puma T-Shirt',
    brand: 'Puma',
    category: 'Clothing',
    type: 'T-Shirt',
    colors: ['Red', 'Black', 'White'],
    sizes: [38, 39, 40, 41],
    price: 25,
    discountPercentage: 20,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 4,
    name: 'Under Armour Shorts',
    brand: 'Under Armour',
    category: 'Clothing',
    type: 'Shorts',
    colors: ['Black', 'Gray', 'Navy'],
    sizes: [38, 39, 40, 41, 42],
    price: 35,
    discountPercentage: 0,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 5,
    name: 'New Balance 990',
    brand: 'New Balance',
    category: 'Shoes',
    type: 'Walking',
    colors: ['Gray', 'Navy'],
    sizes: [37, 38, 40],
    price: 175,
    discountPercentage: 15,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 6,
    name: 'Asics Gel-Kayano',
    brand: 'Asics',
    category: 'Shoes',
    type: 'Running',
    colors: ['Blue', 'White'],
    sizes: [38, 39, 40, 41],
    price: 140,
    discountPercentage: 10,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 7,
    name: 'Nike Revolution 5',
    brand: 'Nike',
    category: 'Shoes',
    type: 'Casual',
    colors: ['Black', 'Gray'],
    sizes: [39, 40, 41, 42],
    price: 60,
    discountPercentage: 5,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 8,
    name: 'Adidas Gazelle',
    brand: 'Adidas',
    category: 'Shoes',
    type: 'Casual',
    colors: ['Green', 'White', 'Yellow'],
    sizes: [38, 39, 40],
    price: 90,
    discountPercentage: 15,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 9,
    name: 'Under Armour T-Shirt',
    brand: 'Under Armour',
    category: 'Clothing',
    type: 'T-Shirt',
    colors: ['White', 'Gray'],
    sizes: [38, 39, 40, 41, 42],
    price: 20,
    discountPercentage: 0,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 10,
    name: 'Reebok Classic',
    brand: 'Reebok',
    category: 'Shoes',
    type: 'Running',
    colors: ['White', 'Blue'],
    sizes: [38, 39, 40, 41],
    price: 85,
    discountPercentage: 20,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 11,
    name: 'Puma Joggers',
    brand: 'Puma',
    category: 'Clothing',
    type: 'Joggers',
    colors: ['Gray', 'Black'],
    sizes: [38, 40, 42],
    price: 50,
    discountPercentage: 10,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 12,
    name: 'New Balance FuelCell',
    brand: 'New Balance',
    category: 'Shoes',
    type: 'Running',
    colors: ['Blue', 'Green'],
    sizes: [37, 38, 39],
    price: 150,
    discountPercentage: 5,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 13,
    name: 'Adidas Adilette Slides',
    brand: 'Adidas',
    category: 'Shoes',
    type: 'Slides',
    colors: ['Black', 'White'],
    sizes: [38, 39, 40, 41],
    price: 25,
    discountPercentage: 0,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 14,
    name: 'Nike Dri-FIT Pants',
    brand: 'Nike',
    category: 'Clothing',
    type: 'Pants',
    colors: ['Black', 'Blue'],
    sizes: [38, 40, 42],
    price: 55,
    discountPercentage: 15,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 15,
    name: 'Puma Track Jacket',
    brand: 'Puma',
    category: 'Clothing',
    type: 'Jacket',
    colors: ['Red', 'White'],
    sizes: [38, 39, 40],
    price: 65,
    discountPercentage: 10,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 16,
    name: 'Under Armour Fleece',
    brand: 'Under Armour',
    category: 'Clothing',
    type: 'Jacket',
    colors: ['Black', 'Gray'],
    sizes: [38, 40, 42],
    price: 70,
    discountPercentage: 5,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 17,
    name: 'Nike Running Shorts',
    brand: 'Nike',
    category: 'Clothing',
    type: 'Shorts',
    colors: ['Blue', 'White'],
    sizes: [38, 39, 40, 41],
    price: 25,
    discountPercentage: 0,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 18,
    name: 'Reebok Nano X',
    brand: 'Reebok',
    category: 'Shoes',
    type: 'Training',
    colors: ['Gray', 'Black'],
    sizes: [38, 39, 40],
    price: 130,
    discountPercentage: 20,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 19,
    name: 'Adidas ZX 2K Boost',
    brand: 'Adidas',
    category: 'Shoes',
    type: 'Casual',
    colors: ['Red', 'Black'],
    sizes: [39, 40, 41, 42],
    price: 150,
    discountPercentage: 10,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 20,
    name: 'Nike Air Force 1',
    brand: 'Nike',
    category: 'Shoes',
    type: 'Casual',
    colors: ['White', 'Blue'],
    sizes: [38, 39, 40, 41],
    price: 100,
    discountPercentage: 5,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 21,
    name: 'Puma Hoodie',
    brand: 'Puma',
    category: 'Clothing',
    type: 'Hoodie',
    colors: ['Black', 'Gray'],
    sizes: [38, 40, 42],
    price: 60,
    discountPercentage: 15,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 22,
    name: 'Under Armour Tights',
    brand: 'Under Armour',
    category: 'Clothing',
    type: 'Tights',
    colors: ['Blue', 'Gray'],
    sizes: [39, 40, 42],
    price: 40,
    discountPercentage: 5,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 23,
    name: 'Adidas NMD R1',
    brand: 'Adidas',
    category: 'Shoes',
    type: 'Running',
    colors: ['Black', 'White'],
    sizes: [39, 40, 41],
    price: 130,
    discountPercentage: 15,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 24,
    name: 'Nike Zoom Pegasus',
    brand: 'Nike',
    category: 'Shoes',
    type: 'Running',
    colors: ['Blue', 'White'],
    sizes: [38, 39, 40],
    price: 120,
    discountPercentage: 10,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 25,
    name: 'Puma Suede Classic',
    brand: 'Puma',
    category: 'Shoes',
    type: 'Casual',
    colors: ['Red', 'Black'],
    sizes: [38, 39, 41],
    price: 70,
    discountPercentage: 5,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 26,
    name: 'New Balance 574',
    brand: 'New Balance',
    category: 'Shoes',
    type: 'Casual',
    colors: ['Gray', 'Blue'],
    sizes: [38, 39, 40],
    price: 80,
    discountPercentage: 10,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 27,
    name: 'Under Armour Tank Top',
    brand: 'Under Armour',
    category: 'Clothing',
    type: 'Tank Top',
    colors: ['Black', 'Blue'],
    sizes: [39, 40, 42],
    price: 25,
    discountPercentage: 0,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 28,
    name: 'Reebok Sweatpants',
    brand: 'Reebok',
    category: 'Clothing',
    type: 'Pants',
    colors: ['Gray', 'Black'],
    sizes: [38, 40, 42],
    price: 45,
    discountPercentage: 5,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 29,
    name: 'Adidas Running Hat',
    brand: 'Adidas',
    category: 'Accessories',
    type: 'Hat',
    colors: ['Black', 'White'],
    sizes: [],
    price: 20,
    discountPercentage: 0,
    image: 'shoes/shoesTest.png',
  },
  {
    id: 30,
    name: 'Nike Crew Socks',
    brand: 'Nike',
    category: 'Accessories',
    type: 'Socks',
    colors: ['White', 'Black'],
    sizes: [],
    price: 10,
    discountPercentage: 10,
    image: 'shoes/shoesTest.png',
  }
];
