// src/app/mock-data/mock-products.ts

import { Product } from '../interface/Product';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Smartphone X',
    price: 999.99,
    colors: ['black', 'white', 'red'],
    type: 'Smartphone',
    brand: 'TechCo',
    category: 'electronics',
    image: 'shoes/0d693d93ff03dd0b_210.jpg',
    discountPercentage: 10,
  },
  {
    id: 2,
    name: 'Laptop Pro',
    price: 1499.99,
    colors: ['silver', 'space gray'],
    type: 'Laptop',
    brand: 'TechCo',
    category: 'electronics',
    image: 'shoes/0dca3bf05bcdd122_210.jpg',
  },
  {
    id: 3,
    name: 'Wireless Earbuds',
    price: 159.99,
    colors: ['white', 'black', 'blue'],
    type: 'Audio',
    brand: 'SoundWave',
    category: 'electronics',
    image: 'shoes/0ed915263fb631ec_210.jpg',
    discountPercentage: 15,
  },
  {
    id: 4,
    name: 'Classic T-Shirt',
    price: 29.99,
    colors: ['white', 'black', 'navy', 'red'],
    type: 'Apparel',
    brand: 'ComfortWear',
    category: 'clothing',
    image: 'shoes/01b1fc5b9bae5edc_210.jpg',
  },
  {
    id: 5,
    name: 'Running Shoes',
    price: 129.99,
    colors: ['black', 'blue', 'red'],
    type: 'Footwear',
    brand: 'SportyFeet',
    category: 'clothing',
    image: 'shoes/01b1fc5b9bae5edc_210.jpg',
    discountPercentage: 20,
  },
  {
    id: 6,
    name: 'Smart Watch',
    price: 299.99,
    colors: ['black', 'silver', 'rose gold'],
    type: 'Wearable',
    brand: 'TechCo',
    category: 'electronics',
    image: 'shoes/1cc17179af994dd8_210.jpg',
  },
  {
    id: 7,
    name: 'Ergonomic Office Chair',
    price: 249.99,
    colors: ['black', 'gray'],
    type: 'Furniture',
    brand: 'ComfortOffice',
    category: 'furniture',
    image: 'shoes/1f0c69a88ae1f9ae_210.jpg',
    discountPercentage: 5,
  },
  {
    id: 8,
    name: '4K Smart TV',
    price: 799.99,
    colors: ['black'],
    type: 'Television',
    brand: 'ViewMaster',
    category: 'electronics',
    image: 'shoes/1fc923cb8da21f7d_210.jpg',
    discountPercentage: 12,
  },
  {
    id: 9,
    name: 'Denim Jeans',
    price: 59.99,
    colors: ['blue', 'black', 'gray'],
    type: 'Apparel',
    brand: 'FashionDenim',
    category: 'clothing',
    image: 'shoes/2a61f3c893af26f3_210.jpg',
  },
  {
    id: 10,
    name: 'Coffee Maker',
    price: 89.99,
    colors: ['silver', 'black'],
    type: 'Appliance',
    brand: 'BrewMaster',
    category: 'home appliances',
    image: 'shoes/2c3c5bd46942b1b5_210.jpg',
    discountPercentage: 8,
  },
  {
    id: 11,
    name: 'Smartphone X',
    price: 999.99,
    colors: ['black', 'white', 'red'],
    type: 'Smartphone',
    brand: 'TechCo',
    category: 'electronics',
    image: 'shoes/0d693d93ff03dd0b_210.jpg',
    discountPercentage: 10,
  },
  {
    id: 12,
    name: 'Laptop Pro',
    price: 1499.99,
    colors: ['silver', 'space gray'],
    type: 'Laptop',
    brand: 'TechCo',
    category: 'electronics',
    image: 'shoes/0dca3bf05bcdd122_210.jpg',
  },
  {
    id: 13,
    name: 'Wireless Earbuds',
    price: 159.99,
    colors: ['white', 'black', 'blue'],
    type: 'Audio',
    brand: 'SoundWave',
    category: 'electronics',
    image: 'shoes/0ed915263fb631ec_210.jpg',
    discountPercentage: 15,
  },
  {
    id: 14,
    name: 'Classic T-Shirt',
    price: 29.99,
    colors: ['white', 'black', 'navy', 'red'],
    type: 'Apparel',
    brand: 'ComfortWear',
    category: 'clothing',
    image: 'shoes/01b1fc5b9bae5edc_210.jpg',
  },
  {
    id: 15,
    name: 'Running Shoes',
    price: 129.99,
    colors: ['black', 'blue', 'red'],
    type: 'Footwear',
    brand: 'SportyFeet',
    category: 'clothing',
    image: 'shoes/01b1fc5b9bae5edc_210.jpg',
    discountPercentage: 20,
  },
  {
    id: 16,
    name: 'Smart Watch',
    price: 299.99,
    colors: ['black', 'silver', 'rose gold'],
    type: 'Wearable',
    brand: 'TechCo',
    category: 'electronics',
    image: 'shoes/1cc17179af994dd8_210.jpg',
  },
  {
    id: 17,
    name: 'Ergonomic Office Chair',
    price: 249.99,
    colors: ['black', 'gray'],
    type: 'Furniture',
    brand: 'ComfortOffice',
    category: 'furniture',
    image: 'shoes/1f0c69a88ae1f9ae_210.jpg',
    discountPercentage: 5,
  },
  {
    id: 18,
    name: '4K Smart TV',
    price: 799.99,
    colors: ['black'],
    type: 'Television',
    brand: 'ViewMaster',
    category: 'electronics',
    image: 'shoes/1fc923cb8da21f7d_210.jpg',
    discountPercentage: 12,
  },
  {
    id: 19,
    name: 'Denim Jeans',
    price: 59.99,
    colors: ['blue', 'black', 'gray'],
    type: 'Apparel',
    brand: 'FashionDenim',
    category: 'clothing',
    image: 'shoes/2a61f3c893af26f3_210.jpg',
  },
  {
    id: 20,
    name: 'Coffee Maker',
    price: 89.99,
    colors: ['silver', 'black'],
    type: 'Appliance',
    brand: 'BrewMaster',
    category: 'home appliances',
    image: 'shoes/2c3c5bd46942b1b5_210.jpg',
    discountPercentage: 8,
  },
  {
    id: 21,
    name: 'Smartphone X',
    price: 999.99,
    colors: ['black', 'white', 'red'],
    type: 'Smartphone',
    brand: 'TechCo',
    category: 'electronics',
    image: 'shoes/0d693d93ff03dd0b_210.jpg',
    discountPercentage: 10,
  },
  {
    id: 22,
    name: 'Laptop Pro',
    price: 1499.99,
    colors: ['silver', 'space gray'],
    type: 'Laptop',
    brand: 'TechCo',
    category: 'electronics',
    image: 'shoes/0dca3bf05bcdd122_210.jpg',
  },
  {
    id: 23,
    name: 'Wireless Earbuds',
    price: 159.99,
    colors: ['white', 'black', 'blue'],
    type: 'Audio',
    brand: 'SoundWave',
    category: 'electronics',
    image: 'shoes/0ed915263fb631ec_210.jpg',
    discountPercentage: 15,
  },
  {
    id: 24,
    name: 'Classic T-Shirt',
    price: 29.99,
    colors: ['white', 'black', 'navy', 'red'],
    type: 'Apparel',
    brand: 'ComfortWear',
    category: 'clothing',
    image: 'shoes/01b1fc5b9bae5edc_210.jpg',
  },
  {
    id: 25,
    name: 'Running Shoes',
    price: 129.99,
    colors: ['black', 'blue', 'red'],
    type: 'Footwear',
    brand: 'SportyFeet',
    category: 'clothing',
    image: 'shoes/01b1fc5b9bae5edc_210.jpg',
    discountPercentage: 20,
  },
  {
    id: 26,
    name: 'Smart Watch',
    price: 299.99,
    colors: ['black', 'silver', 'rose gold'],
    type: 'Wearable',
    brand: 'TechCo',
    category: 'electronics',
    image: 'shoes/1cc17179af994dd8_210.jpg',
  },
  {
    id: 27,
    name: 'Ergonomic Office Chair',
    price: 249.99,
    colors: ['black', 'gray'],
    type: 'Furniture',
    brand: 'ComfortOffice',
    category: 'furniture',
    image: 'shoes/1f0c69a88ae1f9ae_210.jpg',
    discountPercentage: 5,
  },
  {
    id: 28,
    name: '4K Smart TV',
    price: 799.99,
    colors: ['black'],
    type: 'Television',
    brand: 'ViewMaster',
    category: 'electronics',
    image: 'shoes/1fc923cb8da21f7d_210.jpg',
    discountPercentage: 12,
  },
  {
    id: 29,
    name: 'Denim Jeans',
    price: 59.99,
    colors: ['blue', 'black', 'gray'],
    type: 'Apparel',
    brand: 'FashionDenim',
    category: 'clothing',
    image: 'shoes/2a61f3c893af26f3_210.jpg',
  },
  {
    id: 30,
    name: 'Coffee Maker',
    price: 89.99,
    colors: ['silver', 'black'],
    type: 'Appliance',
    brand: 'BrewMaster',
    category: 'home appliances',
    image: 'shoes/2c3c5bd46942b1b5_210.jpg',
    discountPercentage: 8,
  },
  {
    id: 31,
    name: 'Smartphone X',
    price: 999.99,
    colors: ['black', 'white', 'red'],
    type: 'Smartphone',
    brand: 'TechCo',
    category: 'electronics',
    image: 'shoes/0d693d93ff03dd0b_210.jpg',
    discountPercentage: 10,
  },
  {
    id: 32,
    name: 'Laptop Pro',
    price: 1499.99,
    colors: ['silver', 'space gray'],
    type: 'Laptop',
    brand: 'TechCo',
    category: 'electronics',
    image: 'shoes/0dca3bf05bcdd122_210.jpg',
  },
  {
    id: 33,
    name: 'Wireless Earbuds',
    price: 159.99,
    colors: ['white', 'black', 'blue'],
    type: 'Audio',
    brand: 'SoundWave',
    category: 'electronics',
    image: 'shoes/0ed915263fb631ec_210.jpg',
    discountPercentage: 15,
  },
  {
    id: 34,
    name: 'Classic T-Shirt',
    price: 29.99,
    colors: ['white', 'black', 'navy', 'red'],
    type: 'Apparel',
    brand: 'ComfortWear',
    category: 'clothing',
    image: 'shoes/01b1fc5b9bae5edc_210.jpg',
  },
  {
    id: 35,
    name: 'Running Shoes',
    price: 129.99,
    colors: ['black', 'blue', 'red'],
    type: 'Footwear',
    brand: 'SportyFeet',
    category: 'clothing',
    image: 'shoes/01b1fc5b9bae5edc_210.jpg',
    discountPercentage: 20,
  },
  {
    id: 36,
    name: 'Smart Watch',
    price: 299.99,
    colors: ['black', 'silver', 'rose gold'],
    type: 'Wearable',
    brand: 'TechCo',
    category: 'electronics',
    image: 'shoes/1cc17179af994dd8_210.jpg',
  },
  {
    id: 37,
    name: 'Ergonomic Office Chair',
    price: 249.99,
    colors: ['black', 'gray'],
    type: 'Furniture',
    brand: 'ComfortOffice',
    category: 'furniture',
    image: 'shoes/1f0c69a88ae1f9ae_210.jpg',
    discountPercentage: 5,
  },
  {
    id: 38,
    name: '4K Smart TV',
    price: 799.99,
    colors: ['black'],
    type: 'Television',
    brand: 'ViewMaster',
    category: 'electronics',
    image: 'shoes/1fc923cb8da21f7d_210.jpg',
    discountPercentage: 12,
  },
  {
    id: 39,
    name: 'Denim Jeans',
    price: 59.99,
    colors: ['blue', 'black', 'gray'],
    type: 'Apparel',
    brand: 'FashionDenim',
    category: 'clothing',
    image: 'shoes/2a61f3c893af26f3_210.jpg',
  },
  {
    id: 40,
    name: 'Coffee Maker',
    price: 89.99,
    colors: ['silver', 'black'],
    type: 'Appliance',
    brand: 'BrewMaster',
    category: 'home appliances',
    image: 'shoes/2c3c5bd46942b1b5_210.jpg',
    discountPercentage: 8,
  },
];
